import "objidl.idl";
import "oaidl.idl";
import "oleacc.idl";

[
  object,
  uuid(380277A2-64EF-48DB-9DE7-2E0A2D5D6374)
]
interface Bar : IAccessible {

};

[
  object,
  uuid(1579DFCC-F89E-4E12-93DB-A5F41FD68021)
]
interface Foo : IUnknown {

};

[
    uuid(876946BC-AF45-4090-B97D-5D12881FA309),
    hidden
]
library TestLib
{
    importlib ("stdole2.tlb");
    importlib ("oleacc.dll");

    interface Bar;
    interface Foo;
}