import "objidl.idl";
import "oaidl.idl";
import "oleacc.idl";

[
  odl,
  uuid(ff0062e6-a588-4f1e-ad69-331ae7693635)
]
interface IWindow
{
    HRESULT windowHandle(
        [out, retval] WH *handle);
}