typedef struct _FooWindowHandle
{
  long data1;
  long data2;
} FooWindowHandle;

typedef [unique] FooWindowHandle * fooWH;

cpp_quote("#if 0")
typedef [wire_marshal(fooWH)] void* WH;
cpp_quote("#endif // 0")

import "IWindow.idl";

[
    uuid(25ac00c6-7ddd-43d3-ac53-163b6f0a22c1),
    hidden
]
library TestLib
{
    interface IWindow;
}